// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afgoclzvxuvkxypwuqar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZ29jbHp2eHV2a3h5cHd1cWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTY4MDUsImV4cCI6MjA2MjE5MjgwNX0.iGeNUir5X_pTuOFEWQ-hmBdlEKwlwBTUUGpzUkf6WPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);